In [1]:
import numpy as np

def check_consecutive_zeros(matrix):
    # Using np.lib.stride_tricks.sliding_window_view to create a sliding window of size 3 along the rows
    windows = np.lib.stride_tricks.sliding_window_view(matrix, (1,3))
    # Checking if all elements in the window are zero, summing along the last axis and checking if sum is 3
    result_vector = np.any(np.sum(windows == 0, axis=-1) == 3, axis=-1)
    # Converting boolean array to int
    return result_vector.astype(int)

# Example usage
matrix = np.array([[0, 1, 0, 0, 0],
                   [0, 0, 0, 1, 0],
                   [1, 0, 0, 0, 0],
                   [0, 0, 1, 0, 0]])

result_vector = check_consecutive_zeros(matrix)
print(result_vector)


[[0 0 1]
 [1 0 0]
 [0 1 1]
 [0 0 0]]
