In [8]:
import torch
torch.manual_seed(0)

In [9]:
x = torch.randn(3,4)
print(x)

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380],
        [-0.7193, -0.4033, -0.5966,  0.1820]])


In [10]:
y = x.view(2,6)
print(y)

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193, -0.4033, -0.5966,  0.1820]])


In [12]:
z = x.reshape(2,6)
print(z)

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193, -0.4033, -0.5966,  0.1820]])


In [13]:
del x
print(y)

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193, -0.4033, -0.5966,  0.1820]])


In [14]:
print(z)

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193, -0.4033, -0.5966,  0.1820]])


In [17]:
x = torch.randn(10)
y1 = x.view(2,5)
y2 = x.reshape(2,5)


In [22]:
y2.T.reshape(-1)

tensor([ 0.9398, -0.7911,  0.7748, -0.0209,  0.1919, -0.7185,  1.2638,  0.5186,
        -1.2904, -1.3125])